// File: edidslave.v
// Generated by MyHDL 0.9.dev0
// Date: Fri May  1 17:56:52 2015


`timescale 1ns/10ps

module edidslave (
    rst_n,
    clk,
    sda_i,
    sda_o,
    scl_i,
    dvi_only
);


input rst_n;
input clk;
input sda_i;
output sda_o;
reg sda_o;
input scl_i;
input dvi_only;






always @(posedge clk) begin: EDIDSLAVE_RTL
    if (rst_n == 0) begin
        sda_o <= 0;
    end
    else begin
        if (dvi_only) begin
            sda_o <= (sda_i ^ scl_i);
        end
    end
end

endmodule
